nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.10.0-0"
    catalog.cattle.io/display-name: CAPI UI
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
